export interface VehicleInput {
    registrationNumber: string;
    loanAgreementNo?: string;
    registeredOwnerName?: string;
    quoteIncreament?: number | null;
    make?: string;
    model?: string;
    varient?: string;
    category?: string;
    fuel?: string;
    type?: string;
    rcStatus?: string;
    YOM?: number | null;
    ownership?: number | null;
    mileage?: number | null;
    kmReading?: number | null;
    insuranceStatus?: string;
    yardLocation?: string;
    startPrice?: number;
    reservePrice?: number;
    repoDt?: string;
    veicleLocation?: string;
    vehicleRemarks?: string;
    auctionManager?: string;
    parkingCharges?: number;
    insurance?: string;
    insuranceValidTill?: string | null;
    tax?: string;
    taxValidityDate?: string | null;
    fitness?: string;
    permit?: string;
    engineNo?: string;
    chassisNo?: string;
    inspectionLink?: string;
    autobseContact?: string;
    autobse_contact_person?: string;
    vehicleCondition?: string;
    powerSteering?: string;
    shape?: string;
    color?: string;
    state?: string;
    city?: string;
    area?: string;
    paymentTerms?: string;
    dateOfRegistration?: string;
    hypothication?: string;
    climateControl?: string;
    doorCount?: number | null;
    gearBox?: string;
    buyerFees?: string;
    clientContactNo?: string;
    clientContactPerson?: string;
    approxParkingCharges?: number;
    rtoFine?: string;
    additionalRemarks?: string;
    lotNumber?: number;
    image?: string;
  }